kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive --remote

- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  settings:
    repo: ntppool/ntppool
    registry: harbor.ntppool.org
    tags: SHA7,${DRONE_BRANCH}
    auto_tag: true
    cache: true
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
