apiVersion: 0.2.0
environments:
  beta:
    destination:
      namespace: ntpbeta
      server: https://kube-controllers.dev:443
    k8sVersion: v1.8.9
    path: beta
  dev:
    destination:
      namespace: ntpdev
      server: https://192.168.99.100:8443
    k8sVersion: v1.10.0
    path: dev
  docker:
    destination:
      namespace: ntpdev
      server: https://localhost:6443
    k8sVersion: v1.9.6
    path: docker
#  prod:
#    destination:
#      namespace: ntppool
#      server: https://tectonic-api.dev:443
#    k8sVersion: v1.8.9
#    path: prod
  prod:
    destination:
      namespace: ntppool
      server: https://rancher.ewr1.ntppool.com/k8s/clusters/c-5zvsc
    k8sVersion: v1.14.1
    path: prod
kind: ksonnet.io/app
name: ntppool
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
