apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gearmand
  labels:
    app: gearmand
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gearmand
    spec:
      containers:
      - image: pataquets/gearmand
        name: gearmand
        ports:
        - containerPort: 4730
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
