apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splash
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ntppool
        tier: splash
    spec:
      restartPolicy: Always
      containers:
      - name: splash
        image: scrapinghub/splash:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 450Mi
          limits:
            cpu: 1
            memory: 700Mi  
        env:
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: splash
spec:
  ports:
  - name: http
    port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    tier: splash
