apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geoip
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ntppool
        tier: geoip
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "tier"
                    operator: In
                    values:
                    - geoip
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
      containers:
      - name: geoip
        image: quay.io/abh/geoipapi:0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 200Mi  
        env:
        ports:
        - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: geoip
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8009
  selector:
    tier: geoip